### ISSUE TITLE
problem during installation - make pull command

### ISSUE THREAD

**Issue by dhruvbalhara** [srid/discourse-docker#12]
i am installing discourse on server (digitalocean) -ubuntu 13.04 - (1GB mem, 20 GB SSD)
 while installing this error being displayed on passing the command : 
make pull

sudo docker pull srid/discourse-nginx
sudo: docker: command not found
make: **\* [pull] Error 1

**Comment by srid** [comment]
you should install docker (the first step in [README](https://github.com/srid/discourse-docker#usage)) before running anything else, including `make pull`.

**Comment by dhruvbalhara** [comment]
@srid 
In fact i did, i was successfully able to complete the following steps without any error 

open http://docs.docker.io/en/latest/installation/ubuntulinux/#ubuntu-raring
apt-get install postgresql-client
sudo apt-get install python-pip
sudo pip install supervisor
git clone https://github.com/srid/discourse-docker.git
cd discourse-docker

**Comment by srid** [comment]
did you follow the instructions in the first link up including `sudo apt-get install lxc-docker`?
