### ISSUE TITLE
How can I get to the rails console?

### ISSUE THREAD

**Issue by espennilsen** [srid/discourse-docker#13]
The closest I got was with running:  RAILS_ENV=production bundle exec rails c

But it just says "Switch to inspect mode." and exits out.

**Comment by srid** [comment]
i assume that you are running `bin/start-discourse bundle exec rails c` - in which case, we need to pass `-i -t` to `docker run` in [that script](https://github.com/srid/discourse-docker/blob/master/bin/discourse-start#L9). perhaps we can do this using environment variable.

**Comment by espennilsen** [comment]
Yeah that's right. 

But adding -i -t still produces the same output for me.

**Comment by iangcarroll** [comment]
Are you putting -i -t before the `bundle exec` or after?

---

Ian Carroll
Snap Studio Design LLC

**Comment by espennilsen** [comment]
I added it to the bin/start-discourse script right after docker run.

**Comment by srid** [comment]
possibly related to [the enter script](https://github.com/srid/discourse-docker/blob/master/discourse/enter#L30) using `exec bash` to invoke the passed command.

**Comment by srid** [comment]
confirmed. the `enter` script is causing this issue.

```
$ sudo docker run -i -t -e REDIS_PROVIDER_URL=redis://user@192.4.33.22:49160 -e POSTGRES_HOST=192.4.33.22 -e POSTGRES_PORT=49161 -e POSTMARK_API_KEY= -e DISCOURSE_HOST=d.example.com:5000 -v /home/srid/c/discourse-docker/data/discourse-public:/discourse/public -entrypoint=/bin/bash srid/discourse
WARNING: IPv4 forwarding is disabled.
root@bdc3032672c0:/discourse# /enter bundle exec rails c

*** Mocha deprecation warning: Change `require 'mocha'` to `require 'mocha/setup'`.

Loading production environment (Rails 3.2.12)
Switch to inspect mode.

root@bdc3032672c0:/discourse# bundle exec rails c

*** Mocha deprecation warning: Change `require 'mocha'` to `require 'mocha/setup'`.

Loading production environment (Rails 3.2.12)
irb(main):001:0>
```
