### ISSUE TITLE
bin/discourse-start setup

### ISSUE THREAD

**Issue by ZlotaLza** [srid/discourse-docker#18]
bin/discourse-start setup
- exec sudo docker run -e REDIS_PROVIDER_URL=redis://user@192.168.0.138: Usage: docker port CONTAINER PRIVATE_PORT Lookup the public-facing port which is NAT-ed to PRIVATE_PORT -e POSTGRES_HOST=192.168.0.138 -e POSTGRES_PORT= Usage: docker port CONTAINER PRIVATE_PORT Lookup the public-facing port which is NAT-ed to PRIVATE_PORT -e POSTMARK_API_KEY= -e DISCOURSE_HOST=mysite.com:5000 -v /home/bilbo/discourse-docker/data/discourse-public:/discourse/public srid/discourse setup
  Unable to find image 'Usage:' (tag: latest) locally
  2013/11/10 10:33:16 Invalid repository name (Usage), only [a-z0-9-_.] are allowed

I tried localhost, too.

**Comment by srid** [comment]
please try the master branch (which contains more than a few fixes), and file a new bug with the error message you see.
