### ISSUE TITLE
add script to activate accounts / enable mailing

### ISSUE THREAD

**Issue by Finkregh** [srid/discourse-docker#5]
nice scripts so far; the problem at the moment is that i cannot login with my account because the confirmation-email did not get anywhere...

`sh: 1: /usr/sbin/sendmail: not found` in the sidekiq-docker...

you could eventually symlink `sendmail` to `echo` or something... :)

**Comment by srid** [comment]
you could use postmark for email, but it is probably better to configure sendmail by default. pull requests welcome.

note that you can also go to admin preferences and manually activate users.

closing this in favour of issue #7
