### ISSUE TITLE
Nothing but 404's

### ISSUE THREAD

**Issue by imns** [srid/discourse-docker#6]
I followed your doc to a T.  Only thing I did different was that I created my droplet with the Docker on Ubuntu 13.04 Application.  Anyway, when I run `make info` I get the IP address and the url for my site, both are 404's.

**Comment by srid** [comment]
> Only thing I did different was that I created my droplet with the Docker on Ubuntu 13.04 Application

please elaborate; what is different about what you did? are you attempting to run docker inside docker?

> Anyway, when I run make info I get the IP address and the url for my site, both are 404's.

your IP address should be a public one. if not, you can setup a frontend nginx with your site url and proxy to the internal IP (it would be good document this in README).

**Comment by srid** [comment]
i'm closing this bug due to lack of activity. please feel free to re-open if you are still having this issue with latest code in master.
